REQUEST_TIMEOUT = 2.5

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1"
]

PLATFORMS = [
    # --- Social & Microblogging ---
    {'name': 'GitHub', 'url': 'https://github.com/{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'Twitter / X', 'url': 'https://x.com/{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Instagram', 'url': 'https://www.instagram.com/{username}/', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Reddit', 'url': 'https://www.reddit.com/user/{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'TikTok', 'url': 'https://www.tiktok.com/@{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'YouTube', 'url': 'https://www.youtube.com/@{username}', 'error_type': 'status_code', 'category': 'Media'},
    {'name': 'LinkedIn', 'url': 'https://www.linkedin.com/in/{username}/', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Pinterest', 'url': 'https://www.pinterest.com/{username}/', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Threads', 'url': 'https://www.threads.net/@{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Telegram', 'url': 'https://t.me/{username}', 'error_type': 'status_code', 'category': 'Chat'},
    {'name': 'Snapchat', 'url': 'https://www.snapchat.com/add/{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Tumblr', 'url': 'https://{username}.tumblr.com', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'VKontakte', 'url': 'https://vk.com/{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Mastodon.social', 'url': 'https://mastodon.social/@{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Bluesky', 'url': 'https://bsky.app/profile/{username}.bsky.social', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Medium', 'url': 'https://medium.com/@{username}', 'error_type': 'status_code', 'category': 'Blogging'},
    {'name': 'Substack', 'url': 'https://{username}.substack.com', 'error_type': 'status_code', 'category': 'Blogging'},
    {'name': 'Quora', 'url': 'https://www.quora.com/profile/{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Vero', 'url': 'https://vero.co/{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'About.me', 'url': 'https://about.me/{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Keybase', 'url': 'https://keybase.io/{username}', 'error_type': 'status_code', 'category': 'Security'},
    {'name': 'Linktree', 'url': 'https://linktr.ee/{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Bio.link', 'url': 'https://bio.link/{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Carrd', 'url': 'https://{username}.carrd.co', 'error_type': 'status_code', 'category': 'Dev'},

    # --- Developer & Tech ---
    {'name': 'GitLab', 'url': 'https://gitlab.com/{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'BitBucket', 'url': 'https://bitbucket.org/{username}/', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'Replit', 'url': 'https://replit.com/@{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'CodePen', 'url': 'https://codepen.io/{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'HackerNews', 'url': 'https://news.ycombinator.com/user?id={username}', 'error_type': 'message', 'category': 'Dev'},
    {'name': 'ProductHunt', 'url': 'https://www.producthunt.com/@{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'Dev.to', 'url': 'https://dev.to/{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'Hashnode', 'url': 'https://hashnode.com/@{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'SourceForge', 'url': 'https://sourceforge.net/u/{username}/profile/', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'DockerHub', 'url': 'https://hub.docker.com/u/{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'NPM', 'url': 'https://www.npmjs.com/~{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'PyPI', 'url': 'https://pypi.org/user/{username}/', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'Kaggle', 'url': 'https://www.kaggle.com/{username}', 'error_type': 'status_code', 'category': 'Data'},
    {'name': 'LeetCode', 'url': 'https://leetcode.com/{username}/', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'HackerRank', 'url': 'https://www.hackerrank.com/{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'Codeforces', 'url': 'https://codeforces.com/profile/{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'Exercism', 'url': 'https://exercism.org/profiles/{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'Codecademy', 'url': 'https://www.codecademy.com/profiles/{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'StackExchange', 'url': 'https://stackexchange.com/users/filter?search={username}', 'error_type': 'status_code', 'category': 'Dev'},

    # --- Gaming & Streaming ---
    {'name': 'Twitch', 'url': 'https://www.twitch.tv/{username}', 'error_type': 'status_code', 'category': 'Gaming'},
    {'name': 'Steam', 'url': 'https://steamcommunity.com/id/{username}', 'error_type': 'status_code', 'category': 'Gaming'},
    {'name': 'Roblox', 'url': 'https://www.roblox.com/user.aspx?username={username}', 'error_type': 'status_code', 'category': 'Gaming'},
    {'name': 'Kick', 'url': 'https://kick.com/{username}', 'error_type': 'status_code', 'category': 'Gaming'},
    {'name': 'Chess.com', 'url': 'https://www.chess.com/member/{username}', 'error_type': 'status_code', 'category': 'Gaming'},
    {'name': 'Lichess', 'url': 'https://lichess.org/@/{username}', 'error_type': 'status_code', 'category': 'Gaming'},
    {'name': 'osu!', 'url': 'https://osu.ppy.sh/users/{username}', 'error_type': 'status_code', 'category': 'Gaming'},
    {'name': 'Speedrun.com', 'url': 'https://www.speedrun.com/users/{username}', 'error_type': 'status_code', 'category': 'Gaming'},
    {'name': 'NexusMods', 'url': 'https://www.nexusmods.com/users/{username}', 'error_type': 'status_code', 'category': 'Gaming'},
    {'name': 'itch.io', 'url': 'https://{username}.itch.io', 'error_type': 'status_code', 'category': 'Gaming'},
    {'name': 'Letterboxd', 'url': 'https://letterboxd.com/{username}/', 'error_type': 'status_code', 'category': 'Media'},
    {'name': 'MyAnimeList', 'url': 'https://myanimelist.net/profile/{username}', 'error_type': 'status_code', 'category': 'Media'},
    {'name': 'AniList', 'url': 'https://anilist.co/user/{username}/', 'error_type': 'status_code', 'category': 'Media'},
    {'name': 'Trakt', 'url': 'https://trakt.tv/users/{username}', 'error_type': 'status_code', 'category': 'Media'},
    {'name': 'Goodreads', 'url': 'https://www.goodreads.com/{username}', 'error_type': 'status_code', 'category': 'Media'},

    # --- Music & Audio ---
    {'name': 'Spotify', 'url': 'https://open.spotify.com/user/{username}', 'error_type': 'status_code', 'category': 'Music'},
    {'name': 'SoundCloud', 'url': 'https://soundcloud.com/{username}', 'error_type': 'status_code', 'category': 'Music'},
    {'name': 'Bandcamp', 'url': 'https://bandcamp.com/{username}', 'error_type': 'status_code', 'category': 'Music'},
    {'name': 'Last.fm', 'url': 'https://www.last.fm/user/{username}', 'error_type': 'status_code', 'category': 'Music'},
    {'name': 'Audiomack', 'url': 'https://audiomack.com/{username}', 'error_type': 'status_code', 'category': 'Music'},
    {'name': 'Mixcloud', 'url': 'https://www.mixcloud.com/{username}/', 'error_type': 'status_code', 'category': 'Music'},
    {'name': 'Discogs', 'url': 'https://www.discogs.com/user/{username}', 'error_type': 'status_code', 'category': 'Music'},
    {'name': 'Genius', 'url': 'https://genius.com/{username}', 'error_type': 'status_code', 'category': 'Music'},

    # --- Creative, Art & Design ---
    {'name': 'DeviantArt', 'url': 'https://www.deviantart.com/{username}', 'error_type': 'status_code', 'category': 'Art'},
    {'name': 'Behance', 'url': 'https://www.behance.net/{username}', 'error_type': 'status_code', 'category': 'Art'},
    {'name': 'Dribbble', 'url': 'https://dribbble.com/{username}', 'error_type': 'status_code', 'category': 'Art'},
    {'name': 'ArtStation', 'url': 'https://www.artstation.com/{username}', 'error_type': 'status_code', 'category': 'Art'},
    {'name': '500px', 'url': 'https://500px.com/p/{username}', 'error_type': 'status_code', 'category': 'Photo'},
    {'name': 'Flickr', 'url': 'https://www.flickr.com/people/{username}/', 'error_type': 'status_code', 'category': 'Photo'},
    {'name': 'VSCO', 'url': 'https://vsco.co/{username}/gallery', 'error_type': 'status_code', 'category': 'Photo'},
    {'name': 'Unsplash', 'url': 'https://unsplash.com/@{username}', 'error_type': 'status_code', 'category': 'Photo'},
    {'name': 'Imgur', 'url': 'https://imgur.com/user/{username}', 'error_type': 'status_code', 'category': 'Media'},
    {'name': 'Gravatar', 'url': 'https://gravatar.com/{username}', 'error_type': 'status_code', 'category': 'Social'},

    # --- Finance, Crypto & Creator Economy ---
    {'name': 'CashApp', 'url': 'https://cash.app/${username}', 'error_type': 'status_code', 'category': 'Finance'},
    {'name': 'Patreon', 'url': 'https://www.patreon.com/{username}', 'error_type': 'status_code', 'category': 'Creator'},
    {'name': 'BuyMeACoffee', 'url': 'https://www.buymeacoffee.com/{username}', 'error_type': 'status_code', 'category': 'Creator'},
    {'name': 'Ko-fi', 'url': 'https://ko-fi.com/{username}', 'error_type': 'status_code', 'category': 'Creator'},
    {'name': 'Gumroad', 'url': 'https://{username}.gumroad.com', 'error_type': 'status_code', 'category': 'Creator'},
    {'name': 'TradingView', 'url': 'https://www.tradingview.com/u/{username}/', 'error_type': 'status_code', 'category': 'Finance'},
    {'name': 'OpenSea', 'url': 'https://opensea.io/{username}', 'error_type': 'status_code', 'category': 'Crypto'},
    {'name': 'Fiverr', 'url': 'https://www.fiverr.com/{username}', 'error_type': 'status_code', 'category': 'Work'},
    {'name': 'Freelancer', 'url': 'https://www.freelancer.com/u/{username}', 'error_type': 'status_code', 'category': 'Work'},

    # --- Knowledge, Communities & Tools ---
    {'name': 'Instructables', 'url': 'https://www.instructables.com/member/{username}/', 'error_type': 'status_code', 'category': 'DIY'},
    {'name': 'IFTTT', 'url': 'https://ifttt.com/p/{username}', 'error_type': 'status_code', 'category': 'Tools'},
    {'name': 'Duolingo', 'url': 'https://www.duolingo.com/profile/{username}', 'error_type': 'status_code', 'category': 'Learn'},
    {'name': 'Quizlet', 'url': 'https://quizlet.com/{username}', 'error_type': 'status_code', 'category': 'Learn'},
    {'name': 'Pastebin', 'url': 'https://pastebin.com/u/{username}', 'error_type': 'status_code', 'category': 'Tools'},
    {'name': 'Docker', 'url': 'https://docker.com/u/{username}', 'error_type': 'status_code', 'category': 'Dev'},
    {'name': 'Giphy', 'url': 'https://giphy.com/{username}', 'error_type': 'status_code', 'category': 'Media'},
    {'name': 'Tenor', 'url': 'https://tenor.com/users/{username}', 'error_type': 'status_code', 'category': 'Media'},
    {'name': 'Wattpad', 'url': 'https://www.wattpad.com/user/{username}', 'error_type': 'status_code', 'category': 'Writing'},
    {'name': 'Archive.org', 'url': 'https://archive.org/details/@{username}', 'error_type': 'status_code', 'category': 'Archive'},
    {'name': 'Disqus', 'url': 'https://disqus.com/by/{username}/', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'TripAdvisor', 'url': 'https://www.tripadvisor.com/Profile/{username}', 'error_type': 'status_code', 'category': 'Travel'},
    {'name': 'AllTrails', 'url': 'https://www.alltrails.com/members/{username}', 'error_type': 'status_code', 'category': 'Travel'},
    {'name': 'Strava', 'url': 'https://www.strava.com/athletes/{username}', 'error_type': 'status_code', 'category': 'Fitness'},
    {'name': 'MyFitnessPal', 'url': 'https://www.myfitnesspal.com/profile/{username}', 'error_type': 'status_code', 'category': 'Fitness'},
    {'name': 'SmugMug', 'url': 'https://{username}.smugmug.com', 'error_type': 'status_code', 'category': 'Photo'},
    {'name': 'EyeEm', 'url': 'https://www.eyeem.com/u/{username}', 'error_type': 'status_code', 'category': 'Photo'},
    {'name': 'Houzz', 'url': 'https://www.houzz.com/user/{username}', 'error_type': 'status_code', 'category': 'Design'},
    {'name': 'Badoo', 'url': 'https://badoo.com/profile/{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'Mix', 'url': 'https://mix.com/{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': 'WeHeartIt', 'url': 'https://weheartit.com/{username}', 'error_type': 'status_code', 'category': 'Social'},
    {'name': '8tracks', 'url': 'https://8tracks.com/{username}', 'error_type': 'status_code', 'category': 'Music'},
    {'name': 'Plug.dj', 'url': 'https://plug.dj/@/{username}', 'error_type': 'status_code', 'category': 'Music'},
    {'name': 'Vimeo', 'url': 'https://vimeo.com/{username}', 'error_type': 'status_code', 'category': 'Media'},
    {'name': 'Dailymotion', 'url': 'https://www.dailymotion.com/{username}', 'error_type': 'status_code', 'category': 'Media'},
    {'name': 'Rumble', 'url': 'https://rumble.com/user/{username}', 'error_type': 'status_code', 'category': 'Media'},
    {'name': 'Odysee', 'url': 'https://odysee.com/@{username}', 'error_type': 'status_code', 'category': 'Media'}
]
