REQUEST_TIMEOUT = 3

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183"
]

PLATFORMS = [
    {'name': 'GitHub', 'url': 'https://github.com/{username}', 'error_type': 'status_code'},
    {'name': 'Twitter/X', 'url': 'https://x.com/{username}', 'error_type': 'status_code'},
    {'name': 'Instagram', 'url': 'https://www.instagram.com/{username}/', 'error_type': 'status_code'},
    {'name': 'Reddit', 'url': 'https://www.reddit.com/user/{username}', 'error_type': 'status_code'},
    {'name': 'TikTok', 'url': 'https://www.tiktok.com/@{username}', 'error_type': 'status_code'},
    {'name': 'YouTube', 'url': 'https://www.youtube.com/@{username}', 'error_type': 'status_code'},
    {'name': 'LinkedIn', 'url': 'https://www.linkedin.com/in/{username}/', 'error_type': 'status_code'},
    {'name': 'Pinterest', 'url': 'https://www.pinterest.com/{username}/', 'error_type': 'status_code'},
    {'name': 'Twitch', 'url': 'https://www.twitch.tv/{username}', 'error_type': 'status_code'},
    {'name': 'Steam', 'url': 'https://steamcommunity.com/id/{username}', 'error_type': 'status_code'},
    {'name': 'Spotify', 'url': 'https://open.spotify.com/user/{username}', 'error_type': 'status_code'},
    {'name': 'Medium', 'url': 'https://medium.com/@{username}', 'error_type': 'status_code'},
    {'name': 'DeviantArt', 'url': 'https://www.deviantart.com/{username}', 'error_type': 'status_code'},
    {'name': 'Flickr', 'url': 'https://www.flickr.com/people/{username}/', 'error_type': 'status_code'},
    {'name': 'SoundCloud', 'url': 'https://soundcloud.com/{username}', 'error_type': 'status_code'},
    {'name': 'Tumblr', 'url': 'https://{username}.tumblr.com', 'error_type': 'status_code'},
    {'name': 'VK', 'url': 'https://vk.com/{username}', 'error_type': 'status_code'},
    {'name': 'About.me', 'url': 'https://about.me/{username}', 'error_type': 'status_code'},
    {'name': 'Keybase', 'url': 'https://keybase.io/{username}', 'error_type': 'status_code'},
    {'name': 'HackerNews', 'url': 'https://news.ycombinator.com/user?id={username}', 'error_type': 'message'},
    {'name': 'ProductHunt', 'url': 'https://www.producthunt.com/@{username}', 'error_type': 'status_code'},
    {'name': 'Dribbble', 'url': 'https://dribbble.com/{username}', 'error_type': 'status_code'},
    {'name': 'Behance', 'url': 'https://www.behance.net/{username}', 'error_type': 'status_code'},
    {'name': 'GitLab', 'url': 'https://gitlab.com/{username}', 'error_type': 'status_code'},
    {'name': 'BitBucket', 'url': 'https://bitbucket.org/{username}/', 'error_type': 'status_code'},
    {'name': 'Replit', 'url': 'https://replit.com/@{username}', 'error_type': 'status_code'},
    {'name': 'Patreon', 'url': 'https://www.patreon.com/{username}', 'error_type': 'status_code'},
    {'name': 'CashApp', 'url': 'https://cash.app/${username}', 'error_type': 'status_code'},
    {'name': 'Snapchat', 'url': 'https://snapchat.com/add/{username}', 'error_type': 'status_code'},
    {'name': 'Telegram', 'url': 'https://t.me/{username}', 'error_type': 'status_code'},
    {'name': 'Imgur', 'url': 'https://imgur.com/user/{username}', 'error_type': 'status_code'},
    {'name': '500px', 'url': 'https://500px.com/p/{username}', 'error_type': 'status_code'},
    {'name': 'Gravatar', 'url': 'https://gravatar.com/{username}', 'error_type': 'status_code'},
    {'name': 'SourceForge', 'url': 'https://sourceforge.net/u/{username}/profile/', 'error_type': 'status_code'},
    {'name': 'IFTTT', 'url': 'https://ifttt.com/p/{username}', 'error_type': 'status_code'},
    {'name': 'Instructables', 'url': 'https://www.instructables.com/member/{username}/', 'error_type': 'status_code'},
    {'name': 'Codecademy', 'url': 'https://www.codecademy.com/profiles/{username}', 'error_type': 'status_code'},
    {'name': 'TradingView', 'url': 'https://www.tradingview.com/u/{username}/', 'error_type': 'status_code'},
    {'name': 'Roblox', 'url': 'https://www.roblox.com/user.aspx?username={username}', 'error_type': 'status_code'},
]
